name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build
          ref: ${{ github.sha }}

      - name: Do not run if build failed
        run: exit 1
        if: steps.wait-for-build.outputs.conclusion == 'failure'

      - name: Get artifact details
        uses: octokit/request-action@v2.x
        id: get_artifact_details
        with:
          route: GET /repos/${{ github.repository }}/actions/artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send deploy request to host
        id: http_deploy_request
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://webhooks.titan.int.sig.de.labcode.de/update.php?repository=${{ github.repository }}&artifact_id=${{ fromJson(steps.get_artifact_details.outputs.data).artifacts[0].id }}'
          method: 'GET'
          username: ${{ secrets.WEBHOOK_USER }}
          password: ${{ secrets.WEBHOOK_PASSWORD }}
